version: '3.8'
services:
  app:
    build: .
    ports:
      - '5000:5000'
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo:27017/codefusion
      - JWT_SECRET=your_jwt_secret
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
